# Generated by Django 5.2.7 on 2025-10-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del género o categoría', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal de la película', max_length=255)),
                ('titulo_original', models.CharField(blank=True, help_text='Título en su idioma original', max_length=255, null=True)),
                ('link_imdb', models.URLField(help_text='Enlace único de IMDb para evitar duplicados', max_length=500, unique=True)),
                ('estreno', models.PositiveIntegerField(blank=True, help_text='Año de lanzamiento', null=True)),
                ('duracion', models.CharField(blank=True, help_text='Duración en formato texto (ej: 2h 22m)', max_length=50, null=True)),
                ('sinopsis', models.TextField(blank=True, help_text='Resumen o trama de la película', null=True)),
                ('director', models.CharField(blank=True, help_text='Nombre del director', max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Puntuación con un decimal (ej: 8.7)', max_digits=3, null=True)),
                ('poster_url', models.URLField(blank=True, help_text='URL de la imagen del póster', max_length=500, null=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='peliculas', to='principal.categoria')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-estreno', 'titulo'],
            },
        ),
    ]
